### ISSUE TITLE
tap event firing twice on togglable elements

### ISSUE THREAD

**Issue by guanzo** [ngryman/jquery.finger#30] opened 2014-11-11 05:38 UTC
Hey, your script works great except for one thing. It seems that when i tap on togglable elements the tap event is fired twice.

Heres the console log on a tap. The element is shown then immediately hidden.

n.Event {type: "tap", x: 825, y: 36, orientation: null, end: false…} index.js:498
n.Event {originalEvent: n.Event, type: "tap", isDefaultPrevented: function, timeStamp: 1415683966457, jQuery211008474522363394499: true…}
______________________________________________________________________
If i do a press event, the script reads it as a tap and my element is correctly shown/hidden.

n.Event {originalEvent: n.Event, type: "tap", isDefaultPrevented: function, timeStamp: 1415683971257, jQuery211008474522363394499: true…}

**Comment by ngryman** [comment] 2016-06-27 15:07
Closing because no reproducible example and it's kind of old.

**Closed by ngryman** 2016-06-27 15:07 UTC
Labels: standby
